config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: {new: '/'}
    resources :sessions, only: [:new, :create, :destroy],path: '/login', path_names: {new: '/'}
  end
  
  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path:'/'


end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }
  
  has_one_attached :photo
  
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

 
  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages, only: [:index, :show]
  
  def index
    @categories = Category.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index), items: 12)
  end

	def show
		product
	end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end  
  end

  def edit
    authorize! product
  end

  def update
    authorize! product
    if product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end  

  def destroy
    authorize! product
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end
    
  private
  def product_params
    params.require(:product).permit(:title,:description,:price, :photo,:category_id)
  end
    
  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)  
  end

  def product
    @product ||= Product.find(params[:id])
  end

end

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do%>
  <%= category.name%>
<% end%>

app/views/products/_favorite.html.erb
<div id='favorite'>
  <% if @product.favorite %>
    <%= link_to t('.i_dont_like'), favorite_path(product.id), data:{
    turbo_method: :delete
     } %>
  <% else%>
    <%= link_to t('.like'), favorites_path(product_id: product.id), data:{
    turbo_method: :post
    } %>
  <% end %>
</div>  

app/views/products/_form.html.erb
<%= form_with model:@product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
		<div>
			<%= error %>
		</div>
	<% end%>

	<div>
		<%= form.label :title%>
		<%= form.text_field :title%>
	</div>
	<div>
		<%= form.label :description%>
		<%= form.text_area :description%>
	</div>
	<div>
		<%= form.label :price%>
		<%= form.number_field :price%>
	</div>
	<div>
		<%= form.label :photo%>
		<%= form.file_field :photo%>
	</div>
	<div>
		<%= form.label :category_id %>
		<%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
	</div>


	<%= form.submit%>
<%end%>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: 'product', 'data-turbo-frame': '_top' do %> 
  <%= image_tag product.photo, width: 100 if product.photo.attached? %>
  <h2><%= product.title  %> </h2>
  <span><%= product.price %> </span>
<% end %>

app/views/products/edit.html.erb
<h2><%= t('.title')%></h2>


<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do%>
  <h1><%= t('.title')%></h1>

  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
    <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price]%>
    <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price]%>

    <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %>
  <%end%>

  <%= link_to t('.all'), products_path %>
  <%= render partial: 'category', collection: @categories %>
 
  <%= turbo_frame_tag :products do %>
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
      <%= render partial: 'product', collection: @products %>
      <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title')%> </h2>

<%= render 'form' %>

app/views/products/show.html.erb
<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<h1 class='title'><%=@product.title %> </h1>

<p class= 'description'><%=@product.description %> </p>

<h2 class='price'>$<%=@product.price %></h2>

<%= link_to t('.edit'), edit_product_path(@product) if @product.owner? %>

<%= link_to t('.delete'), product_path(@product), data:{
   turbo_method: :delete,
   turbo_confirm: t('common.confirm')
   } if @product.owner? %>

<%= link_to t('.view_more_products', username: @product.user.username ), user_path(@product.user.username)%>   

<%= render partial: 'favorite', locals: { product: @product} %>

